project_id = "daajdwzrmtjrlkmtmsie"

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "https://daajdwzrmtjrlkmtmsie.supabase.co/auth/v1/callback"
url = ""